version: '3'

services:
  master:
    build:
      context: .
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
  
  worker:
    build:
      context: .
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker 4 --master-host master
